#file: noinspection undefined
server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quanlyda
    username: root
    password: 8082
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

com:
  hcv:
    jwt:
      secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

