#file: noinspection undefined
server:
  port: 8888

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/quanlyda}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:8082}
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

com:
  hcv:
    jwt:
      secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      valid-duration: 3600 # in seconds
      refreshable-duration: 864000 # in seconds

